# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'panel.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Panel(object):
    def setupUi(self, Panel):
        Panel.setObjectName("Panel")
        Panel.resize(2461, 1287)
        font = QtGui.QFont()
        font.setFamily("Arial")
        Panel.setFont(font)
        Panel.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.centralwidget = QtWidgets.QWidget(Panel)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_menu = QtWidgets.QFrame(self.centralwidget)
        self.frame_menu.setGeometry(QtCore.QRect(50, 180, 1721, 611))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.frame_menu.setFont(font)
        self.frame_menu.setStyleSheet("background-color: rgba(46, 46, 46, 0.9);\n"
"border-radius: 10px;")
        self.frame_menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_menu.setObjectName("frame_menu")
        self.btnclose = QtWidgets.QPushButton(self.frame_menu)
        self.btnclose.setGeometry(QtCore.QRect(1677, 10, 18, 18))
        self.btnclose.setMinimumSize(QtCore.QSize(18, 18))
        self.btnclose.setMaximumSize(QtCore.QSize(18, 18))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.btnclose.setFont(font)
        self.btnclose.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnclose.setStyleSheet("background-color: rgb(230, 0, 0);\n"
"border-radius: 8px;")
        self.btnclose.setText("")
        self.btnclose.setObjectName("btnclose")
        self.btnmini = QtWidgets.QPushButton(self.frame_menu)
        self.btnmini.setGeometry(QtCore.QRect(1641, 10, 18, 18))
        self.btnmini.setMinimumSize(QtCore.QSize(18, 18))
        self.btnmini.setMaximumSize(QtCore.QSize(18, 18))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.btnmini.setFont(font)
        self.btnmini.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnmini.setStyleSheet("background-color: rgb(230, 230, 0);\n"
"border-radius: 8px;")
        self.btnmini.setText("")
        self.btnmini.setObjectName("btnmini")
        self.btn_home_page = QtWidgets.QPushButton(self.frame_menu)
        self.btn_home_page.setGeometry(QtCore.QRect(20, 93, 301, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setItalic(True)
        self.btn_home_page.setFont(font)
        self.btn_home_page.setStyleSheet("QPushButton{\n"
"    border-radius: 20px;\n"
"    background-color: #fff;\n"
"    color: #000;\n"
"    border: 1px solid #fff;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: #fff;\n"
"    color: black;\n"
"}\n"
"")
        self.btn_home_page.setObjectName("btn_home_page")
        self.btn_insert_page = QtWidgets.QPushButton(self.frame_menu)
        self.btn_insert_page.setGeometry(QtCore.QRect(20, 203, 301, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setItalic(True)
        self.btn_insert_page.setFont(font)
        self.btn_insert_page.setStyleSheet("QPushButton{\n"
"    border-radius: 20px;\n"
"    background-color: none;\n"
"    color: #fff;\n"
"    border: 1px solid #fff;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: #fff;\n"
"    color: black;\n"
"}\n"
"")
        self.btn_insert_page.setObjectName("btn_insert_page")
        self.btn_setting_page = QtWidgets.QPushButton(self.frame_menu)
        self.btn_setting_page.setGeometry(QtCore.QRect(20, 323, 301, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setItalic(True)
        self.btn_setting_page.setFont(font)
        self.btn_setting_page.setStyleSheet("QPushButton{\n"
"    border-radius: 20px;\n"
"    background-color: none;\n"
"    color: #fff;\n"
"    border: 1px solid #fff;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: #fff;\n"
"    color: black;\n"
"}\n"
"")
        self.btn_setting_page.setObjectName("btn_setting_page")
        self.btn_about_page = QtWidgets.QPushButton(self.frame_menu)
        self.btn_about_page.setGeometry(QtCore.QRect(20, 443, 301, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setItalic(True)
        self.btn_about_page.setFont(font)
        self.btn_about_page.setStyleSheet("QPushButton{\n"
"    border-radius: 20px;\n"
"    background-color: none;\n"
"    color: #fff;\n"
"    border: 1px solid #fff;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: #fff;\n"
"    color: black;\n"
"}\n"
"")
        self.btn_about_page.setObjectName("btn_about_page")
        self.label_5 = QtWidgets.QLabel(self.frame_menu)
        self.label_5.setGeometry(QtCore.QRect(40, 530, 221, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: #CAB8FF;\n"
"padding: 5px;\n"
"background-color: none;")
        self.label_5.setObjectName("label_5")
        self.label_user = QtWidgets.QLabel(self.frame_menu)
        self.label_user.setGeometry(QtCore.QRect(125, 11, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_user.setFont(font)
        self.label_user.setStyleSheet("QLabel {\n"
"    border: 1px solid rgb(255, 255, 255);\n"
"    background-color: none;\n"
"    color: #fff;\n"
"    border-radius: 10px;\n"
"\n"
"\n"
"}\n"
"QLabel:hover {\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0)\n"
"}")
        self.label_user.setText("")
        self.label_user.setObjectName("label_user")
        self.frame_panel = QtWidgets.QFrame(self.centralwidget)
        self.frame_panel.setGeometry(QtCore.QRect(350, 120, 1321, 851))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.frame_panel.setFont(font)
        self.frame_panel.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 20px;\n"
"")
        self.frame_panel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_panel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_panel.setObjectName("frame_panel")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_panel)
        self.stackedWidget.setGeometry(QtCore.QRect(9, 9, 1311, 831))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.stackedWidget.setFont(font)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_home = QtWidgets.QWidget()
        self.page_home.setObjectName("page_home")
        self.label = QtWidgets.QLabel(self.page_home)
        self.label.setGeometry(QtCore.QRect(620, 0, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setStyleSheet("color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgb(121, 56, 242), stop:1 rgb(43, 1, 121));")
        self.label.setObjectName("label")
        self.tableView_data = QtWidgets.QTableView(self.page_home)
        self.tableView_data.setGeometry(QtCore.QRect(25, 380, 911, 421))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.tableView_data.setFont(font)
        self.tableView_data.setStyleSheet("alternate-background-color: #E2E2E2;\n"
"background: #CAB8FF;\n"
"border-radius: 6px;")
        self.tableView_data.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableView_data.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableView_data.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableView_data.setAlternatingRowColors(True)
        self.tableView_data.setObjectName("tableView_data")
        self.groupBox_filter = QtWidgets.QGroupBox(self.page_home)
        self.groupBox_filter.setGeometry(QtCore.QRect(20, 50, 511, 231))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.groupBox_filter.setFont(font)
        self.groupBox_filter.setStyleSheet("background-color: #E2E2E2;")
        self.groupBox_filter.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_filter.setObjectName("groupBox_filter")
        self.btn_filter = QtWidgets.QPushButton(self.groupBox_filter)
        self.btn_filter.setGeometry(QtCore.QRect(380, 170, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setItalic(True)
        self.btn_filter.setFont(font)
        self.btn_filter.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_filter.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgb(121, 56, 242), stop:1 rgb(43, 1, 121));\n"
"    color: #fff;\n"
"    border-radius: 6px;\n"
"\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #41295a, stop:1 #2F0743);\n"
"}")
        self.btn_filter.setObjectName("btn_filter")
        self.label_3 = QtWidgets.QLabel(self.groupBox_filter)
        self.label_3.setGeometry(QtCore.QRect(338, 31, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgb(121, 56, 242), stop:1 rgb(43, 1, 121));\n"
"background-color: none;")
        self.label_3.setObjectName("label_3")
        self.comboBox_category = QtWidgets.QComboBox(self.groupBox_filter)
        self.comboBox_category.setGeometry(QtCore.QRect(313, 95, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.comboBox_category.setFont(font)
        self.comboBox_category.setStyleSheet("border: 1px solid qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgb(121, 56, 242), stop:1 rgb(43, 1, 121));;\n"
"background-color: #E2E2E2;\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 6px;")
        self.comboBox_category.setMaxVisibleItems(100)
        self.comboBox_category.setObjectName("comboBox_category")
        self.comboBox_category.addItem("")
        self.label_2 = QtWidgets.QLabel(self.groupBox_filter)
        self.label_2.setGeometry(QtCore.QRect(28, 40, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgb(121, 56, 242), stop:1 rgb(43, 1, 121));\n"
"background-color: none;")
        self.label_2.setObjectName("label_2")
        self.comboBox_period = QtWidgets.QComboBox(self.groupBox_filter)
        self.comboBox_period.setGeometry(QtCore.QRect(28, 100, 221, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.comboBox_period.setFont(font)
        self.comboBox_period.setStyleSheet("border: 1px solid qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgb(121, 56, 242), stop:1 rgb(43, 1, 121));;\n"
"background-color: #E2E2E2;\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 6px;")
        self.comboBox_period.setCurrentText("")
        self.comboBox_period.setMaxVisibleItems(100)
        self.comboBox_period.setObjectName("comboBox_period")
        self.label_filter_error = QtWidgets.QLabel(self.groupBox_filter)
        self.label_filter_error.setGeometry(QtCore.QRect(30, 160, 331, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.label_filter_error.setFont(font)
        self.label_filter_error.setStyleSheet("color: rgb(255, 6, 51);\n"
"background-color: none;")
        self.label_filter_error.setText("")
        self.label_filter_error.setObjectName("label_filter_error")
        self.textEdit_description = QtWidgets.QTextEdit(self.page_home)
        self.textEdit_description.setGeometry(QtCore.QRect(954, 520, 341, 271))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.textEdit_description.setFont(font)
        self.textEdit_description.setStyleSheet("background-color: #CAB8FF;\n"
"border-radius: 10px;")
        self.textEdit_description.setReadOnly(True)
        self.textEdit_description.setObjectName("textEdit_description")
        self.groupBox_options = QtWidgets.QGroupBox(self.page_home)
        self.groupBox_options.setGeometry(QtCore.QRect(1150, 30, 151, 261))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.groupBox_options.setFont(font)
        self.groupBox_options.setStyleSheet("background-color: #E2E2E2;")
        self.groupBox_options.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_options.setObjectName("groupBox_options")
        self.btn_export_csv = QtWidgets.QPushButton(self.groupBox_options)
        self.btn_export_csv.setGeometry(QtCore.QRect(18, 20, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setItalic(True)
        self.btn_export_csv.setFont(font)
        self.btn_export_csv.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_export_csv.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgb(121, 56, 242), stop:1 rgb(43, 1, 121));\n"
"    color: #fff;\n"
"    border-radius: 6px;\n"
"\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #41295a, stop:1 #2F0743);\n"
"}")
        self.btn_export_csv.setObjectName("btn_export_csv")
        self.btn_chart = QtWidgets.QPushButton(self.groupBox_options)
        self.btn_chart.setGeometry(QtCore.QRect(20, 70, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setItalic(True)
        self.btn_chart.setFont(font)
        self.btn_chart.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_chart.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgb(121, 56, 242), stop:1 rgb(43, 1, 121));\n"
"    color: #fff;\n"
"    border-radius: 6px;\n"
"\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #41295a, stop:1 #2F0743);\n"
"}")
        self.btn_chart.setObjectName("btn_chart")
        self.btn_delete = QtWidgets.QPushButton(self.groupBox_options)
        self.btn_delete.setGeometry(QtCore.QRect(20, 190, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setItalic(True)
        self.btn_delete.setFont(font)
        self.btn_delete.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_delete.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgb(121, 56, 242), stop:1 rgb(43, 1, 121));\n"
"    color: #fff;\n"
"    border-radius: 6px;\n"
"\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #41295a, stop:1 #2F0743);\n"
"}")
        self.btn_delete.setObjectName("btn_delete")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox_options)
        self.radioButton.setGeometry(QtCore.QRect(19, 160, 95, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.radioButton.setFont(font)
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox_options)
        self.radioButton_2.setGeometry(QtCore.QRect(19, 140, 95, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.radioButton_2.setFont(font)
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(self.groupBox_options)
        self.radioButton_3.setGeometry(QtCore.QRect(19, 120, 95, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.radioButton_3.setFont(font)
        self.radioButton_3.setChecked(True)
        self.radioButton_3.setObjectName("radioButton_3")
        self.progressBar = QtWidgets.QProgressBar(self.page_home)
        self.progressBar.setGeometry(QtCore.QRect(30, 308, 811, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.progressBar.setFont(font)
        self.progressBar.setStyleSheet("QProgressBar::chunk{\n"
"    border-radius: 15px;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #11998e, stop:1 #38ef7d);\n"
"\n"
"}\n"
"\n"
"QProgressBar{\n"
"    color: #ffff;\n"
"    border-style: none;\n"
"    border-radius: 15px;\n"
"    text-align: center;\n"
"    height: 40px;\n"
"    background-color: #ccccff;\n"
"}")
        self.progressBar.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.tableWidget = QtWidgets.QTableWidget(self.page_home)
        self.tableWidget.setGeometry(QtCore.QRect(960, 394, 321, 91))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.tableWidget.setFont(font)
        self.tableWidget.setStyleSheet("background: #ccccff;\n"
"border-radius: 6px;")
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.dateEdit_search = QtWidgets.QDateEdit(self.page_home)
        self.dateEdit_search.setGeometry(QtCore.QRect(950, 317, 351, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        self.dateEdit_search.setFont(font)
        self.dateEdit_search.setStyleSheet("QDateEdit{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: none;\n"
"    border-bottom: 3px solid qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgb(121, 56, 242), stop:1 rgb(43, 1, 121));\n"
"    border-radius: none;\n"
"}\n"
"QDateEdit:focus{\n"
"    border-bottom: 3px solid qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #41295a, stop:1 #2F0743);\n"
"}")
        self.dateEdit_search.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.dateEdit_search.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.dateEdit_search.setTimeSpec(QtCore.Qt.LocalTime)
        self.dateEdit_search.setObjectName("dateEdit_search")
        self.btn_search = QtWidgets.QPushButton(self.page_home)
        self.btn_search.setGeometry(QtCore.QRect(1159, 321, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setItalic(True)
        self.btn_search.setFont(font)
        self.btn_search.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_search.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgb(121, 56, 242), stop:1 rgb(43, 1, 121));\n"
"    color: #fff;\n"
"    border-radius: 6px;\n"
"\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #41295a, stop:1 #2F0743);\n"
"}")
        self.btn_search.setObjectName("btn_search")
        self.label_delete_error = QtWidgets.QLabel(self.page_home)
        self.label_delete_error.setGeometry(QtCore.QRect(950, 806, 341, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.label_delete_error.setFont(font)
        self.label_delete_error.setStyleSheet("color: rgb(255, 6, 51);\n"
"background-color: none;")
        self.label_delete_error.setText("")
        self.label_delete_error.setObjectName("label_delete_error")
        self.tableView_budget = QtWidgets.QTableView(self.page_home)
        self.tableView_budget.setGeometry(QtCore.QRect(542, 58, 451, 221))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.tableView_budget.setFont(font)
        self.tableView_budget.setStyleSheet("alternate-background-color: #E2E2E2;\n"
"background: #CAB8FF;\n"
"border-radius: 6px;")
        self.tableView_budget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableView_budget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableView_budget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableView_budget.setAlternatingRowColors(True)
        self.tableView_budget.setObjectName("tableView_budget")
        self.tableView_category = QtWidgets.QTableView(self.page_home)
        self.tableView_category.setGeometry(QtCore.QRect(1006, 60, 131, 221))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.tableView_category.setFont(font)
        self.tableView_category.setStyleSheet("alternate-background-color: #E2E2E2;\n"
"background: #CAB8FF;\n"
"border-radius: 6px;")
        self.tableView_category.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableView_category.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableView_category.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableView_category.setAlternatingRowColors(True)
        self.tableView_category.setObjectName("tableView_category")
        self.btn_refresh = QtWidgets.QPushButton(self.page_home)
        self.btn_refresh.setGeometry(QtCore.QRect(853, 313, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setItalic(True)
        self.btn_refresh.setFont(font)
        self.btn_refresh.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_refresh.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgb(121, 56, 242), stop:1 rgb(43, 1, 121));\n"
"    color: #fff;\n"
"    border-radius: 9px;\n"
"\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #41295a, stop:1 #2F0743);\n"
"}")
        self.btn_refresh.setObjectName("btn_refresh")
        self.stackedWidget.addWidget(self.page_home)
        self.page_insert = QtWidgets.QWidget()
        self.page_insert.setObjectName("page_insert")
        self.groupBox = QtWidgets.QGroupBox(self.page_insert)
        self.groupBox.setGeometry(QtCore.QRect(550, 470, 721, 331))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("background-color: #E2E2E2;")
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName("groupBox")
        self.dateEdit_from_budget = QtWidgets.QDateEdit(self.groupBox)
        self.dateEdit_from_budget.setGeometry(QtCore.QRect(120, 90, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        self.dateEdit_from_budget.setFont(font)
        self.dateEdit_from_budget.setStyleSheet("QDateEdit{\n"
"    background-color: #E2E2E2;\n"
"    border: none;\n"
"    border-bottom: 3px solid qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgb(121, 56, 242), stop:1 rgb(43, 1, 121));\n"
"    border-radius: none;\n"
"}\n"
"QDateEdit:focus{\n"
"    border-bottom: 3px solid qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #41295a, stop:1 #2F0743);\n"
"}")
        self.dateEdit_from_budget.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.dateEdit_from_budget.setTimeSpec(QtCore.Qt.LocalTime)
        self.dateEdit_from_budget.setObjectName("dateEdit_from_budget")
        self.dateEdit_to_budget = QtWidgets.QDateEdit(self.groupBox)
        self.dateEdit_to_budget.setGeometry(QtCore.QRect(121, 210, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        self.dateEdit_to_budget.setFont(font)
        self.dateEdit_to_budget.setStyleSheet("QDateEdit{\n"
"    background-color: #E2E2E2;\n"
"    border: none;\n"
"    border-bottom: 3px solid qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgb(121, 56, 242), stop:1 rgb(43, 1, 121));\n"
"    border-radius: none;\n"
"}\n"
"QDateEdit:focus{\n"
"    border-bottom: 3px solid qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #41295a, stop:1 #2F0743);\n"
"}")
        self.dateEdit_to_budget.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.dateEdit_to_budget.setTimeSpec(QtCore.Qt.LocalTime)
        self.dateEdit_to_budget.setObjectName("dateEdit_to_budget")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(36, 50, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: none;")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(40, 168, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: none;")
        self.label_8.setObjectName("label_8")
        self.lineEdit_insert_budget = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_insert_budget.setGeometry(QtCore.QRect(360, 160, 311, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lineEdit_insert_budget.setFont(font)
        self.lineEdit_insert_budget.setStyleSheet("QLineEdit{\n"
"    background-color: #E2E2E2;\n"
"    border: none;\n"
"    border-bottom: 3px solid qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgb(121, 56, 242), stop:1 rgb(43, 1, 121));\n"
"    border-radius: none;\n"
"}\n"
"QLineEdit:focus{\n"
"    border-bottom: 3px solid qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #41295a, stop:1 #2F0743);\n"
"}\n"
"")
        self.lineEdit_insert_budget.setObjectName("lineEdit_insert_budget")
        self.btn_insert_budget = QtWidgets.QPushButton(self.groupBox)
        self.btn_insert_budget.setGeometry(QtCore.QRect(570, 260, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setItalic(True)
        self.btn_insert_budget.setFont(font)
        self.btn_insert_budget.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_insert_budget.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgb(121, 56, 242), stop:1 rgb(43, 1, 121));\n"
"    color: #fff;\n"
"    border-radius: 6px;\n"
"\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #41295a, stop:1 #2F0743);\n"
"}")
        self.btn_insert_budget.setObjectName("btn_insert_budget")
        self.label_insert_budget_error = QtWidgets.QLabel(self.groupBox)
        self.label_insert_budget_error.setGeometry(QtCore.QRect(20, 270, 451, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.label_insert_budget_error.setFont(font)
        self.label_insert_budget_error.setStyleSheet("color: rgb(255, 6, 51);\n"
"background-color: none;")
        self.label_insert_budget_error.setText("")
        self.label_insert_budget_error.setObjectName("label_insert_budget_error")
        self.lineEdit_insert_budget_name = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_insert_budget_name.setGeometry(QtCore.QRect(360, 50, 311, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lineEdit_insert_budget_name.setFont(font)
        self.lineEdit_insert_budget_name.setStyleSheet("QLineEdit{\n"
"    background-color: #E2E2E2;\n"
"    border: none;\n"
"    border-bottom: 3px solid qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgb(121, 56, 242), stop:1 rgb(43, 1, 121));\n"
"    border-radius: none;\n"
"}\n"
"QLineEdit:focus{\n"
"    border-bottom: 3px solid qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #41295a, stop:1 #2F0743);\n"
"}\n"
"")
        self.lineEdit_insert_budget_name.setObjectName("lineEdit_insert_budget_name")
        self.label_6 = QtWidgets.QLabel(self.page_insert)
        self.label_6.setGeometry(QtCore.QRect(629, 0, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgb(121, 56, 242), stop:1 rgb(43, 1, 121));")
        self.label_6.setObjectName("label_6")
        self.groupBox_2 = QtWidgets.QGroupBox(self.page_insert)
        self.groupBox_2.setGeometry(QtCore.QRect(40, 490, 481, 271))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setStyleSheet("background-color: #E2E2E2;")
        self.groupBox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_2.setObjectName("groupBox_2")
        self.lineEdit_insert_category = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_insert_category.setGeometry(QtCore.QRect(30, 50, 291, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lineEdit_insert_category.setFont(font)
        self.lineEdit_insert_category.setStyleSheet("QLineEdit{\n"
"    background-color: #E2E2E2;\n"
"    border: none;\n"
"    border-bottom: 3px solid qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgb(121, 56, 242), stop:1 rgb(43, 1, 121));\n"
"    border-radius: none;\n"
"}\n"
"QLineEdit:focus{\n"
"    border-bottom: 3px solid qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #41295a, stop:1 #2F0743);\n"
"}\n"
"")
        self.lineEdit_insert_category.setObjectName("lineEdit_insert_category")
        self.btn_insert_category = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_insert_category.setGeometry(QtCore.QRect(320, 200, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setItalic(True)
        self.btn_insert_category.setFont(font)
        self.btn_insert_category.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_insert_category.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgb(121, 56, 242), stop:1 rgb(43, 1, 121));\n"
"    color: #fff;\n"
"    border-radius: 6px;\n"
"\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #41295a, stop:1 #2F0743);\n"
"}")
        self.btn_insert_category.setObjectName("btn_insert_category")
        self.btn_color = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_color.setGeometry(QtCore.QRect(380, 60, 61, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setItalic(True)
        self.btn_color.setFont(font)
        self.btn_color.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_color.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgb(121, 56, 242), stop:1 rgb(43, 1, 121));\n"
"    color: #fff;\n"
"    border-radius: 20px;\n"
"\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #41295a, stop:1 #2F0743);\n"
"}")
        self.btn_color.setObjectName("btn_color")
        self.label_insert_category = QtWidgets.QLabel(self.groupBox_2)
        self.label_insert_category.setGeometry(QtCore.QRect(10, 210, 291, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.label_insert_category.setFont(font)
        self.label_insert_category.setStyleSheet("color: rgb(255, 6, 51);\n"
"background-color: none;")
        self.label_insert_category.setText("")
        self.label_insert_category.setObjectName("label_insert_category")
        self.groupBox_3 = QtWidgets.QGroupBox(self.page_insert)
        self.groupBox_3.setGeometry(QtCore.QRect(40, 80, 1231, 291))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setStyleSheet("background-color: #E2E2E2;")
        self.groupBox_3.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_3.setObjectName("groupBox_3")
        self.btn_insert_amount = QtWidgets.QPushButton(self.groupBox_3)
        self.btn_insert_amount.setGeometry(QtCore.QRect(1060, 220, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setItalic(True)
        self.btn_insert_amount.setFont(font)
        self.btn_insert_amount.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_insert_amount.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgb(121, 56, 242), stop:1 rgb(43, 1, 121));\n"
"    color: #fff;\n"
"    border-radius: 6px;\n"
"\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #41295a, stop:1 #2F0743);\n"
"}")
        self.btn_insert_amount.setObjectName("btn_insert_amount")
        self.comboBox_period_insert = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_period_insert.setGeometry(QtCore.QRect(30, 60, 211, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.comboBox_period_insert.setFont(font)
        self.comboBox_period_insert.setStyleSheet("border: 1px solid qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgb(121, 56, 242), stop:1 rgb(43, 1, 121));;\n"
"background-color: #E2E2E2;\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 6px;")
        self.comboBox_period_insert.setCurrentText("")
        self.comboBox_period_insert.setMaxVisibleItems(100)
        self.comboBox_period_insert.setObjectName("comboBox_period_insert")
        self.dateEdit_insert_amount = QtWidgets.QDateEdit(self.groupBox_3)
        self.dateEdit_insert_amount.setGeometry(QtCore.QRect(850, 30, 211, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        self.dateEdit_insert_amount.setFont(font)
        self.dateEdit_insert_amount.setStyleSheet("background-color: #CAB8FF;\n"
"border-radius: 10px;")
        self.dateEdit_insert_amount.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.dateEdit_insert_amount.setTimeSpec(QtCore.Qt.LocalTime)
        self.dateEdit_insert_amount.setObjectName("dateEdit_insert_amount")
        self.textEdit_description_insert = QtWidgets.QTextEdit(self.groupBox_3)
        self.textEdit_description_insert.setGeometry(QtCore.QRect(390, 40, 311, 181))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.textEdit_description_insert.setFont(font)
        self.textEdit_description_insert.setStyleSheet("background-color: #CAB8FF;\n"
"border-radius: 10px;")
        self.textEdit_description_insert.setObjectName("textEdit_description_insert")
        self.lineEdit_insert_amount = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_insert_amount.setGeometry(QtCore.QRect(30, 150, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lineEdit_insert_amount.setFont(font)
        self.lineEdit_insert_amount.setStyleSheet("QLineEdit{\n"
"    background-color: #E2E2E2;\n"
"    border: none;\n"
"    border-bottom: 3px solid qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgb(121, 56, 242), stop:1 rgb(43, 1, 121));\n"
"    border-radius: none;\n"
"}\n"
"QLineEdit:focus{\n"
"    border-bottom: 3px solid qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #41295a, stop:1 #2F0743);\n"
"}\n"
"")
        self.lineEdit_insert_amount.setObjectName("lineEdit_insert_amount")
        self.label_insert_amount_error = QtWidgets.QLabel(self.groupBox_3)
        self.label_insert_amount_error.setGeometry(QtCore.QRect(60, 230, 831, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.label_insert_amount_error.setFont(font)
        self.label_insert_amount_error.setStyleSheet("color: rgb(255, 6, 51);\n"
"background-color: none;")
        self.label_insert_amount_error.setText("")
        self.label_insert_amount_error.setObjectName("label_insert_amount_error")
        self.comboBox_category_insert = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_category_insert.setGeometry(QtCore.QRect(850, 140, 221, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.comboBox_category_insert.setFont(font)
        self.comboBox_category_insert.setStyleSheet("border: 1px solid qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgb(121, 56, 242), stop:1 rgb(43, 1, 121));;\n"
"background-color: #E2E2E2;\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 6px;")
        self.comboBox_category_insert.setCurrentText("")
        self.comboBox_category_insert.setMaxVisibleItems(100)
        self.comboBox_category_insert.setObjectName("comboBox_category_insert")
        self.stackedWidget.addWidget(self.page_insert)
        self.page_setting = QtWidgets.QWidget()
        self.page_setting.setObjectName("page_setting")
        self.groupBox_4 = QtWidgets.QGroupBox(self.page_setting)
        self.groupBox_4.setGeometry(QtCore.QRect(470, 530, 371, 191))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setStyleSheet("background-color: #E2E2E2;")
        self.groupBox_4.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_4.setObjectName("groupBox_4")
        self.btn_dark = QtWidgets.QPushButton(self.groupBox_4)
        self.btn_dark.setGeometry(QtCore.QRect(248, 50, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setItalic(True)
        self.btn_dark.setFont(font)
        self.btn_dark.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_dark.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    background-color: #202020;\n"
"    color: #fff;\n"
"    border-radius: 20px;\n"
"\n"
"\n"
"}\n"
"")
        self.btn_dark.setText("")
        self.btn_dark.setObjectName("btn_dark")
        self.btn_light = QtWidgets.QPushButton(self.groupBox_4)
        self.btn_light.setGeometry(QtCore.QRect(85, 50, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setItalic(True)
        self.btn_light.setFont(font)
        self.btn_light.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_light.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    background-color: #fff;\n"
"    color: #fff;\n"
"    border-radius: 20px;\n"
"\n"
"\n"
"}\n"
"")
        self.btn_light.setText("")
        self.btn_light.setObjectName("btn_light")
        self.label_9 = QtWidgets.QLabel(self.groupBox_4)
        self.label_9.setGeometry(QtCore.QRect(65, 110, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.groupBox_4)
        self.label_10.setGeometry(QtCore.QRect(248, 110, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("")
        self.label_10.setObjectName("label_10")
        self.label_4 = QtWidgets.QLabel(self.page_setting)
        self.label_4.setGeometry(QtCore.QRect(610, 0, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgb(121, 56, 242), stop:1 rgb(43, 1, 121));")
        self.label_4.setObjectName("label_4")
        self.groupBox_5 = QtWidgets.QGroupBox(self.page_setting)
        self.groupBox_5.setGeometry(QtCore.QRect(180, 170, 931, 331))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setStyleSheet("background-color: #E2E2E2;")
        self.groupBox_5.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_5.setObjectName("groupBox_5")
        self.btn_logout = QtWidgets.QPushButton(self.groupBox_5)
        self.btn_logout.setGeometry(QtCore.QRect(50, 48, 301, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setItalic(True)
        self.btn_logout.setFont(font)
        self.btn_logout.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_logout.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgb(121, 56, 242), stop:1 rgb(43, 1, 121));\n"
"    color: #fff;\n"
"    border-radius: 6px;\n"
"\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #41295a, stop:1 #2F0743);\n"
"}")
        self.btn_logout.setObjectName("btn_logout")
        self.btn_delete_account = QtWidgets.QPushButton(self.groupBox_5)
        self.btn_delete_account.setGeometry(QtCore.QRect(50, 121, 301, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setItalic(True)
        self.btn_delete_account.setFont(font)
        self.btn_delete_account.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_delete_account.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgb(121, 56, 242), stop:1 rgb(43, 1, 121));\n"
"    color: #fff;\n"
"    border-radius: 6px;\n"
"\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #41295a, stop:1 #2F0743);\n"
"}")
        self.btn_delete_account.setObjectName("btn_delete_account")
        self.checkBox_sure = QtWidgets.QCheckBox(self.groupBox_5)
        self.checkBox_sure.setGeometry(QtCore.QRect(130, 180, 141, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.checkBox_sure.setFont(font)
        self.checkBox_sure.setObjectName("checkBox_sure")
        self.lineEdit_change_username = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_change_username.setGeometry(QtCore.QRect(550, 120, 331, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lineEdit_change_username.setFont(font)
        self.lineEdit_change_username.setStyleSheet("QLineEdit{\n"
"    background-color: #E2E2E2;\n"
"    border: none;\n"
"    border-bottom: 3px solid qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgb(121, 56, 242), stop:1 rgb(43, 1, 121));\n"
"    border-radius: none;\n"
"}\n"
"QLineEdit:focus{\n"
"    border-bottom: 3px solid qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #41295a, stop:1 #2F0743);\n"
"}\n"
"")
        self.lineEdit_change_username.setObjectName("lineEdit_change_username")
        self.label_11 = QtWidgets.QLabel(self.groupBox_5)
        self.label_11.setGeometry(QtCore.QRect(620, 20, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("")
        self.label_11.setObjectName("label_11")
        self.btn_change_username = QtWidgets.QPushButton(self.groupBox_5)
        self.btn_change_username.setGeometry(QtCore.QRect(660, 280, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setItalic(True)
        self.btn_change_username.setFont(font)
        self.btn_change_username.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_change_username.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgb(121, 56, 242), stop:1 rgb(43, 1, 121));\n"
"    color: #fff;\n"
"    border-radius: 6px;\n"
"\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #41295a, stop:1 #2F0743);\n"
"}")
        self.btn_change_username.setObjectName("btn_change_username")
        self.label_account_setting_error = QtWidgets.QLabel(self.groupBox_5)
        self.label_account_setting_error.setGeometry(QtCore.QRect(30, 260, 581, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.label_account_setting_error.setFont(font)
        self.label_account_setting_error.setStyleSheet("color: rgb(255, 6, 51);\n"
"background-color: none;")
        self.label_account_setting_error.setText("")
        self.label_account_setting_error.setObjectName("label_account_setting_error")
        self.lineEdit_change_email = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_change_email.setGeometry(QtCore.QRect(550, 200, 331, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lineEdit_change_email.setFont(font)
        self.lineEdit_change_email.setStyleSheet("QLineEdit{\n"
"    background-color: #E2E2E2;\n"
"    border: none;\n"
"    border-bottom: 3px solid qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgb(121, 56, 242), stop:1 rgb(43, 1, 121));\n"
"    border-radius: none;\n"
"}\n"
"QLineEdit:focus{\n"
"    border-bottom: 3px solid qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #41295a, stop:1 #2F0743);\n"
"}\n"
"")
        self.lineEdit_change_email.setObjectName("lineEdit_change_email")
        self.checkBox_email = QtWidgets.QCheckBox(self.groupBox_5)
        self.checkBox_email.setGeometry(QtCore.QRect(550, 50, 61, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.checkBox_email.setFont(font)
        self.checkBox_email.setObjectName("checkBox_email")
        self.checkBox_username = QtWidgets.QCheckBox(self.groupBox_5)
        self.checkBox_username.setGeometry(QtCore.QRect(550, 80, 91, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.checkBox_username.setFont(font)
        self.checkBox_username.setObjectName("checkBox_username")
        self.stackedWidget.addWidget(self.page_setting)
        self.page_about = QtWidgets.QWidget()
        self.page_about.setObjectName("page_about")
        self.btn_contact = QtWidgets.QPushButton(self.page_about)
        self.btn_contact.setGeometry(QtCore.QRect(480, 650, 331, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setItalic(True)
        self.btn_contact.setFont(font)
        self.btn_contact.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_contact.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgb(121, 56, 242), stop:1 rgb(43, 1, 121));\n"
"    color: #fff;\n"
"    border-radius: 20px;\n"
"\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #41295a, stop:1 #2F0743);\n"
"}")
        self.btn_contact.setObjectName("btn_contact")
        self.groupBox_6 = QtWidgets.QGroupBox(self.page_about)
        self.groupBox_6.setGeometry(QtCore.QRect(120, 80, 1041, 521))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setStyleSheet("background-color: #E2E2E2;")
        self.groupBox_6.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_6.setObjectName("groupBox_6")
        self.textEdit_description_2 = QtWidgets.QTextEdit(self.groupBox_6)
        self.textEdit_description_2.setGeometry(QtCore.QRect(57, 60, 921, 401))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.textEdit_description_2.setFont(font)
        self.textEdit_description_2.setStyleSheet("background-color: #E2E2E2;\n"
"border-radius: 10px;")
        self.textEdit_description_2.setReadOnly(True)
        self.textEdit_description_2.setObjectName("textEdit_description_2")
        self.groupBox_7 = QtWidgets.QGroupBox(self.page_about)
        self.groupBox_7.setGeometry(QtCore.QRect(320, 770, 661, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.groupBox_7.setFont(font)
        self.groupBox_7.setStyleSheet("background-color: #E2E2E2;\n"
"")
        self.groupBox_7.setTitle("")
        self.groupBox_7.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_7.setObjectName("groupBox_7")
        self.label_12 = QtWidgets.QLabel(self.groupBox_7)
        self.label_12.setGeometry(QtCore.QRect(160, 10, 431, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.page_about)
        self.label_13.setGeometry(QtCore.QRect(630, 10, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgb(121, 56, 242), stop:1 rgb(43, 1, 121));")
        self.label_13.setObjectName("label_13")
        self.stackedWidget.addWidget(self.page_about)
        Panel.setCentralWidget(self.centralwidget)

        self.retranslateUi(Panel)
        self.stackedWidget.setCurrentIndex(0)
        self.btnclose.clicked.connect(Panel.close)
        self.btnmini.clicked['bool'].connect(Panel.showMinimized)
        QtCore.QMetaObject.connectSlotsByName(Panel)

    def retranslateUi(self, Panel):
        _translate = QtCore.QCoreApplication.translate
        Panel.setWindowTitle(_translate("Panel", "MainWindow"))
        self.btn_home_page.setText(_translate("Panel", "Home"))
        self.btn_insert_page.setText(_translate("Panel", "Insert"))
        self.btn_setting_page.setText(_translate("Panel", "Settings"))
        self.btn_about_page.setText(_translate("Panel", "About"))
        self.label_5.setText(_translate("Panel", "Accounting app"))
        self.label.setText(_translate("Panel", "Home"))
        self.groupBox_filter.setTitle(_translate("Panel", "Filter"))
        self.btn_filter.setText(_translate("Panel", "Filter"))
        self.label_3.setText(_translate("Panel", "category"))
        self.comboBox_category.setCurrentText(_translate("Panel", "All"))
        self.comboBox_category.setItemText(0, _translate("Panel", "All"))
        self.label_2.setText(_translate("Panel", "Time suffering *"))
        self.textEdit_description.setHtml(_translate("Panel", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.groupBox_options.setTitle(_translate("Panel", "Options"))
        self.btn_export_csv.setText(_translate("Panel", "Export csv"))
        self.btn_chart.setText(_translate("Panel", "Chart"))
        self.btn_delete.setText(_translate("Panel", "Delete"))
        self.radioButton.setText(_translate("Panel", "Budget"))
        self.radioButton_2.setText(_translate("Panel", "Category"))
        self.radioButton_3.setText(_translate("Panel", "Data"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("Panel", ">>>"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Panel", "Budget"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Panel", "Amount"))
        self.dateEdit_search.setDisplayFormat(_translate("Panel", "yyyy-MM-dd"))
        self.btn_search.setText(_translate("Panel", "Search"))
        self.btn_refresh.setText(_translate("Panel", "Refresh"))
        self.groupBox.setTitle(_translate("Panel", "period budget"))
        self.dateEdit_from_budget.setDisplayFormat(_translate("Panel", "yyyy-MM-dd"))
        self.dateEdit_to_budget.setDisplayFormat(_translate("Panel", "yyyy-MM-dd"))
        self.label_7.setText(_translate("Panel", "from:"))
        self.label_8.setText(_translate("Panel", "to:"))
        self.lineEdit_insert_budget.setPlaceholderText(_translate("Panel", "Budget:"))
        self.btn_insert_budget.setText(_translate("Panel", "Insert"))
        self.lineEdit_insert_budget_name.setPlaceholderText(_translate("Panel", "Name:"))
        self.label_6.setText(_translate("Panel", "Insert"))
        self.groupBox_2.setTitle(_translate("Panel", "Category"))
        self.lineEdit_insert_category.setPlaceholderText(_translate("Panel", "Category name:"))
        self.btn_insert_category.setText(_translate("Panel", "Insert"))
        self.btn_color.setText(_translate("Panel", "Color"))
        self.groupBox_3.setTitle(_translate("Panel", "Expenditures"))
        self.btn_insert_amount.setText(_translate("Panel", "Insert"))
        self.dateEdit_insert_amount.setDisplayFormat(_translate("Panel", "yyyy-MM-dd"))
        self.textEdit_description_insert.setPlaceholderText(_translate("Panel", "Description:"))
        self.lineEdit_insert_amount.setPlaceholderText(_translate("Panel", "Amount:"))
        self.groupBox_4.setTitle(_translate("Panel", "Theme"))
        self.label_9.setText(_translate("Panel", "Light"))
        self.label_10.setText(_translate("Panel", "Dark"))
        self.label_4.setText(_translate("Panel", "Setting"))
        self.groupBox_5.setTitle(_translate("Panel", "Account"))
        self.btn_logout.setText(_translate("Panel", "Log out"))
        self.btn_delete_account.setText(_translate("Panel", "Delete account"))
        self.checkBox_sure.setText(_translate("Panel", "Are you sure ?"))
        self.lineEdit_change_username.setPlaceholderText(_translate("Panel", "Username:"))
        self.label_11.setText(_translate("Panel", "Change username"))
        self.btn_change_username.setText(_translate("Panel", "Change"))
        self.lineEdit_change_email.setPlaceholderText(_translate("Panel", "Email:"))
        self.checkBox_email.setText(_translate("Panel", "Email"))
        self.checkBox_username.setText(_translate("Panel", "Username"))
        self.btn_contact.setText(_translate("Panel", "Contact me"))
        self.groupBox_6.setTitle(_translate("Panel", "About"))
        self.textEdit_description_2.setHtml(_translate("Panel", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">With the help of this accounting application, you can set the desired budget for several time periods and manage your account with the categories you have created.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">There is also the possibility of exporting in Excel file and graphic charts for your convenience.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">You can also create multiple accounts and manage them. Don\'t worry about forgetting your password because we have a password recovery system.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Good luck ..</p></body></html>"))
        self.label_12.setText(_translate("Panel", "Made with 💖 and ☕ by \"M A. N. I\""))
        self.label_13.setText(_translate("Panel", "About"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Panel = QtWidgets.QMainWindow()
    ui = Ui_Panel()
    ui.setupUi(Panel)
    Panel.show()
    sys.exit(app.exec_())
