# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_login_signup(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(939, 578)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(80, 140, 791, 301))
        self.frame.setStyleSheet("background-color: rgba(46, 46, 46, 0.95);\n"
"border-radius: 10px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.btnmini = QtWidgets.QPushButton(self.frame)
        self.btnmini.setGeometry(QtCore.QRect(730, 10, 18, 18))
        self.btnmini.setMinimumSize(QtCore.QSize(18, 18))
        self.btnmini.setMaximumSize(QtCore.QSize(18, 18))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnmini.setFont(font)
        self.btnmini.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnmini.setStyleSheet("background-color: rgb(230, 230, 0);\n"
"border-radius: 8px;")
        self.btnmini.setText("")
        self.btnmini.setObjectName("btnmini")
        self.btnclose = QtWidgets.QPushButton(self.frame)
        self.btnclose.setGeometry(QtCore.QRect(760, 10, 18, 18))
        self.btnclose.setMinimumSize(QtCore.QSize(18, 18))
        self.btnclose.setMaximumSize(QtCore.QSize(18, 18))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnclose.setFont(font)
        self.btnclose.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnclose.setStyleSheet("background-color: rgb(230, 0, 0);\n"
"border-radius: 8px;")
        self.btnclose.setText("")
        self.btnclose.setObjectName("btnclose")
        self.stackedWidget_2 = QtWidgets.QStackedWidget(self.frame)
        self.stackedWidget_2.setGeometry(QtCore.QRect(499, 39, 281, 251))
        self.stackedWidget_2.setStyleSheet("opacity: 0.95;")
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.label_2 = QtWidgets.QLabel(self.page)
        self.label_2.setGeometry(QtCore.QRect(40, 10, 191, 61))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: none;\n"
"color: rgb(255, 255, 255);")
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.btnchangesignup = QtWidgets.QPushButton(self.page)
        self.btnchangesignup.setGeometry(QtCore.QRect(90, 140, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setItalic(True)
        self.btnchangesignup.setFont(font)
        self.btnchangesignup.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnchangesignup.setStyleSheet("QPushButton{\n"
"    border-radius: 6px;\n"
"    background-color: none;\n"
"    color: #fff;\n"
"    border: 1px solid #fff;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: #fff;\n"
"    color: black;\n"
"}")
        self.btnchangesignup.setObjectName("btnchangesignup")
        self.stackedWidget_2.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.label_7 = QtWidgets.QLabel(self.page_2)
        self.label_7.setGeometry(QtCore.QRect(20, 10, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(14)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("background-color: none;\n"
"color: rgb(255, 255, 255);")
        self.label_7.setWordWrap(True)
        self.label_7.setObjectName("label_7")
        self.btnchangelogin = QtWidgets.QPushButton(self.page_2)
        self.btnchangelogin.setGeometry(QtCore.QRect(90, 140, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setItalic(True)
        self.btnchangelogin.setFont(font)
        self.btnchangelogin.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnchangelogin.setStyleSheet("QPushButton{\n"
"    border-radius: 6px;\n"
"    background-color: none;\n"
"    color: #fff;\n"
"    border: 1px solid #fff;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: #fff;\n"
"    color: black;\n"
"}")
        self.btnchangelogin.setObjectName("btnchangelogin")
        self.stackedWidget_2.addWidget(self.page_2)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(160, 60, 411, 461))
        self.frame_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 15px;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_2)
        self.stackedWidget.setGeometry(QtCore.QRect(9, 9, 391, 441))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_login = QtWidgets.QWidget()
        self.page_login.setObjectName("page_login")
        self.label = QtWidgets.QLabel(self.page_login)
        self.label.setGeometry(QtCore.QRect(20, 20, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setStyleSheet("color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgb(121, 56, 242), stop:1 rgb(43, 1, 121));")
        self.label.setObjectName("label")
        self.lblusername = QtWidgets.QLineEdit(self.page_login)
        self.lblusername.setGeometry(QtCore.QRect(22, 110, 351, 41))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(12)
        self.lblusername.setFont(font)
        self.lblusername.setStyleSheet("QLineEdit{\n"
"    border: none;\n"
"    border-bottom: 3px solid qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgb(121, 56, 242), stop:1 rgb(43, 1, 121));\n"
"    border-radius: none;\n"
"}\n"
"QLineEdit:focus{\n"
"    border-bottom: 3px solid qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #41295a, stop:1 #2F0743);\n"
"}")
        self.lblusername.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.lblusername.setObjectName("lblusername")
        self.lblpassword = QtWidgets.QLineEdit(self.page_login)
        self.lblpassword.setGeometry(QtCore.QRect(20, 230, 351, 41))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(12)
        self.lblpassword.setFont(font)
        self.lblpassword.setStyleSheet("QLineEdit{\n"
"    border: none;\n"
"    border-bottom: 3px solid qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgb(121, 56, 242), stop:1 rgb(43, 1, 121));\n"
"    border-radius: none;\n"
"}\n"
"QLineEdit:focus{\n"
"    border-bottom: 3px solid qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #41295a, stop:1 #2F0743);\n"
"}")
        self.lblpassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lblpassword.setObjectName("lblpassword")
        self.btnlogin = QtWidgets.QPushButton(self.page_login)
        self.btnlogin.setGeometry(QtCore.QRect(260, 356, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setItalic(True)
        self.btnlogin.setFont(font)
        self.btnlogin.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnlogin.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgb(121, 56, 242), stop:1 rgb(43, 1, 121));\n"
"    color: #fff;\n"
"    border-radius: 6px;\n"
"\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #41295a, stop:1 #2F0743);\n"
"}")
        self.btnlogin.setObjectName("btnlogin")
        self.label_4 = QtWidgets.QLabel(self.page_login)
        self.label_4.setGeometry(QtCore.QRect(10, 403, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(7)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_4.setObjectName("label_4")
        self.btnforgopass = QtWidgets.QPushButton(self.page_login)
        self.btnforgopass.setGeometry(QtCore.QRect(162, 414, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setBold(True)
        font.setWeight(75)
        self.btnforgopass.setFont(font)
        self.btnforgopass.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnforgopass.setStyleSheet("background-color: none;\n"
"color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgb(121, 56, 242), stop:1 rgb(43, 1, 121));")
        self.btnforgopass.setObjectName("btnforgopass")
        self.label_login_error = QtWidgets.QLabel(self.page_login)
        self.label_login_error.setGeometry(QtCore.QRect(20, 290, 351, 41))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(10)
        self.label_login_error.setFont(font)
        self.label_login_error.setStyleSheet("color: rgb(255, 8, 53);")
        self.label_login_error.setText("")
        self.label_login_error.setWordWrap(True)
        self.label_login_error.setObjectName("label_login_error")
        self.stackedWidget.addWidget(self.page_login)
        self.page_forgot = QtWidgets.QWidget()
        self.page_forgot.setObjectName("page_forgot")
        self.lbl_forgo_username = QtWidgets.QLineEdit(self.page_forgot)
        self.lbl_forgo_username.setGeometry(QtCore.QRect(20, 160, 351, 41))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(12)
        self.lbl_forgo_username.setFont(font)
        self.lbl_forgo_username.setStyleSheet("QLineEdit{\n"
"    border: none;\n"
"    border-bottom: 3px solid qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgb(121, 56, 242), stop:1 rgb(43, 1, 121));\n"
"    border-radius: none;\n"
"}\n"
"QLineEdit:focus{\n"
"    border-bottom: 3px solid qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #41295a, stop:1 #2F0743);\n"
"}")
        self.lbl_forgo_username.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.lbl_forgo_username.setObjectName("lbl_forgo_username")
        self.label_5 = QtWidgets.QLabel(self.page_forgot)
        self.label_5.setGeometry(QtCore.QRect(20, 20, 351, 41))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(18)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgb(121, 56, 242), stop:1 rgb(43, 1, 121));")
        self.label_5.setObjectName("label_5")
        self.btnnext = QtWidgets.QPushButton(self.page_forgot)
        self.btnnext.setGeometry(QtCore.QRect(250, 350, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setItalic(True)
        self.btnnext.setFont(font)
        self.btnnext.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnnext.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgb(121, 56, 242), stop:1 rgb(43, 1, 121));\n"
"    color: #fff;\n"
"    border-radius: 6px;\n"
"\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #41295a, stop:1 #2F0743);\n"
"}")
        self.btnnext.setObjectName("btnnext")
        self.label_forgot_error = QtWidgets.QLabel(self.page_forgot)
        self.label_forgot_error.setGeometry(QtCore.QRect(20, 240, 351, 41))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(10)
        self.label_forgot_error.setFont(font)
        self.label_forgot_error.setStyleSheet("color: rgb(255, 8, 53);")
        self.label_forgot_error.setText("")
        self.label_forgot_error.setWordWrap(True)
        self.label_forgot_error.setObjectName("label_forgot_error")
        self.stackedWidget.addWidget(self.page_forgot)
        self.page_code = QtWidgets.QWidget()
        self.page_code.setObjectName("page_code")
        self.lblfcode = QtWidgets.QLineEdit(self.page_code)
        self.lblfcode.setGeometry(QtCore.QRect(20, 160, 351, 41))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(12)
        self.lblfcode.setFont(font)
        self.lblfcode.setStyleSheet("QLineEdit{\n"
"    border: none;\n"
"    border-bottom: 3px solid qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgb(121, 56, 242), stop:1 rgb(43, 1, 121));\n"
"    border-radius: none;\n"
"}\n"
"QLineEdit:focus{\n"
"    border-bottom: 3px solid qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #41295a, stop:1 #2F0743);\n"
"}")
        self.lblfcode.setText("")
        self.lblfcode.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.lblfcode.setObjectName("lblfcode")
        self.label_8 = QtWidgets.QLabel(self.page_code)
        self.label_8.setGeometry(QtCore.QRect(30, 30, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(18)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgb(121, 56, 242), stop:1 rgb(43, 1, 121));")
        self.label_8.setObjectName("label_8")
        self.btncheck_2 = QtWidgets.QPushButton(self.page_code)
        self.btncheck_2.setGeometry(QtCore.QRect(240, 360, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setItalic(True)
        self.btncheck_2.setFont(font)
        self.btncheck_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btncheck_2.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgb(121, 56, 242), stop:1 rgb(43, 1, 121));\n"
"    color: #fff;\n"
"    border-radius: 6px;\n"
"\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #41295a, stop:1 #2F0743);\n"
"}")
        self.btncheck_2.setObjectName("btncheck_2")
        self.label_code_error = QtWidgets.QLabel(self.page_code)
        self.label_code_error.setGeometry(QtCore.QRect(20, 240, 351, 41))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(10)
        self.label_code_error.setFont(font)
        self.label_code_error.setStyleSheet("color: rgb(255, 8, 53);")
        self.label_code_error.setText("")
        self.label_code_error.setWordWrap(True)
        self.label_code_error.setObjectName("label_code_error")
        self.stackedWidget.addWidget(self.page_code)
        self.page_reset_pass = QtWidgets.QWidget()
        self.page_reset_pass.setObjectName("page_reset_pass")
        self.lblnewpass = QtWidgets.QLineEdit(self.page_reset_pass)
        self.lblnewpass.setGeometry(QtCore.QRect(26, 110, 351, 41))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(12)
        self.lblnewpass.setFont(font)
        self.lblnewpass.setStyleSheet("QLineEdit{\n"
"    border: none;\n"
"    border-bottom: 3px solid qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgb(121, 56, 242), stop:1 rgb(43, 1, 121));\n"
"    border-radius: none;\n"
"}\n"
"QLineEdit:focus{\n"
"    border-bottom: 3px solid qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #41295a, stop:1 #2F0743);\n"
"}")
        self.lblnewpass.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lblnewpass.setObjectName("lblnewpass")
        self.lblnewpassre = QtWidgets.QLineEdit(self.page_reset_pass)
        self.lblnewpassre.setGeometry(QtCore.QRect(26, 230, 351, 41))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(12)
        self.lblnewpassre.setFont(font)
        self.lblnewpassre.setStyleSheet("QLineEdit{\n"
"    border: none;\n"
"    border-bottom: 3px solid qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgb(121, 56, 242), stop:1 rgb(43, 1, 121));\n"
"    border-radius: none;\n"
"}\n"
"QLineEdit:focus{\n"
"    border-bottom: 3px solid qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #41295a, stop:1 #2F0743);\n"
"}")
        self.lblnewpassre.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lblnewpassre.setObjectName("lblnewpassre")
        self.btnsub = QtWidgets.QPushButton(self.page_reset_pass)
        self.btnsub.setGeometry(QtCore.QRect(240, 360, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setItalic(True)
        self.btnsub.setFont(font)
        self.btnsub.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnsub.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgb(121, 56, 242), stop:1 rgb(43, 1, 121));\n"
"    color: #fff;\n"
"    border-radius: 6px;\n"
"\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #41295a, stop:1 #2F0743);\n"
"}")
        self.btnsub.setObjectName("btnsub")
        self.label_6 = QtWidgets.QLabel(self.page_reset_pass)
        self.label_6.setGeometry(QtCore.QRect(30, 20, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(18)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgb(121, 56, 242), stop:1 rgb(43, 1, 121));")
        self.label_6.setObjectName("label_6")
        self.label_reset_error = QtWidgets.QLabel(self.page_reset_pass)
        self.label_reset_error.setGeometry(QtCore.QRect(28, 300, 351, 41))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(10)
        self.label_reset_error.setFont(font)
        self.label_reset_error.setStyleSheet("color: rgb(255, 8, 53);")
        self.label_reset_error.setText("")
        self.label_reset_error.setWordWrap(True)
        self.label_reset_error.setObjectName("label_reset_error")
        self.stackedWidget.addWidget(self.page_reset_pass)
        self.page_signup = QtWidgets.QWidget()
        self.page_signup.setObjectName("page_signup")
        self.lbluser = QtWidgets.QLineEdit(self.page_signup)
        self.lbluser.setGeometry(QtCore.QRect(20, 80, 351, 41))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(12)
        self.lbluser.setFont(font)
        self.lbluser.setStyleSheet("QLineEdit{\n"
"    border: none;\n"
"    border-bottom: 3px solid qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgb(121, 56, 242), stop:1 rgb(43, 1, 121));\n"
"    border-radius: none;\n"
"}\n"
"QLineEdit:focus{\n"
"    border-bottom: 3px solid qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #41295a, stop:1 #2F0743);\n"
"}")
        self.lbluser.setObjectName("lbluser")
        self.lblpass = QtWidgets.QLineEdit(self.page_signup)
        self.lblpass.setGeometry(QtCore.QRect(20, 220, 351, 41))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(12)
        self.lblpass.setFont(font)
        self.lblpass.setStyleSheet("QLineEdit{\n"
"    border: none;\n"
"    border-bottom: 3px solid qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgb(121, 56, 242), stop:1 rgb(43, 1, 121));\n"
"    border-radius: none;\n"
"}\n"
"QLineEdit:focus{\n"
"    border-bottom: 3px solid qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #41295a, stop:1 #2F0743);\n"
"}")
        self.lblpass.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lblpass.setObjectName("lblpass")
        self.btnsignup = QtWidgets.QPushButton(self.page_signup)
        self.btnsignup.setGeometry(QtCore.QRect(260, 390, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setItalic(True)
        self.btnsignup.setFont(font)
        self.btnsignup.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnsignup.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgb(121, 56, 242), stop:1 rgb(43, 1, 121));\n"
"    color: #fff;\n"
"    border-radius: 6px;\n"
"\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #41295a, stop:1 #2F0743);\n"
"}")
        self.btnsignup.setObjectName("btnsignup")
        self.label_3 = QtWidgets.QLabel(self.page_signup)
        self.label_3.setGeometry(QtCore.QRect(20, 20, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(18)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgb(121, 56, 242), stop:1 rgb(43, 1, 121));")
        self.label_3.setObjectName("label_3")
        self.lblemail = QtWidgets.QLineEdit(self.page_signup)
        self.lblemail.setGeometry(QtCore.QRect(20, 150, 351, 41))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(12)
        self.lblemail.setFont(font)
        self.lblemail.setStyleSheet("QLineEdit{\n"
"    border: none;\n"
"    border-bottom: 3px solid qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgb(121, 56, 242), stop:1 rgb(43, 1, 121));\n"
"    border-radius: none;\n"
"}\n"
"QLineEdit:focus{\n"
"    border-bottom: 3px solid qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #41295a, stop:1 #2F0743);\n"
"}")
        self.lblemail.setObjectName("lblemail")
        self.lblrepeatpass = QtWidgets.QLineEdit(self.page_signup)
        self.lblrepeatpass.setGeometry(QtCore.QRect(20, 290, 351, 41))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(12)
        self.lblrepeatpass.setFont(font)
        self.lblrepeatpass.setStyleSheet("QLineEdit{\n"
"    border: none;\n"
"    border-bottom: 3px solid qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgb(121, 56, 242), stop:1 rgb(43, 1, 121));\n"
"    border-radius: none;\n"
"}\n"
"QLineEdit:focus{\n"
"    border-bottom: 3px solid qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #41295a, stop:1 #2F0743);\n"
"}")
        self.lblrepeatpass.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lblrepeatpass.setObjectName("lblrepeatpass")
        self.label_signup_error = QtWidgets.QLabel(self.page_signup)
        self.label_signup_error.setGeometry(QtCore.QRect(20, 340, 351, 41))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(10)
        self.label_signup_error.setFont(font)
        self.label_signup_error.setStyleSheet("color: rgb(255, 8, 53);")
        self.label_signup_error.setText("")
        self.label_signup_error.setWordWrap(True)
        self.label_signup_error.setObjectName("label_signup_error")
        self.stackedWidget.addWidget(self.page_signup)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget_2.setCurrentIndex(0)
        self.stackedWidget.setCurrentIndex(0)
        self.btnclose.clicked.connect(MainWindow.close)
        self.btnmini.clicked.connect(MainWindow.showMinimized)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Do not have an account ?"))
        self.btnchangesignup.setText(_translate("MainWindow", "signup"))
        self.label_7.setText(_translate("MainWindow", "have an account ?"))
        self.btnchangelogin.setText(_translate("MainWindow", "login"))
        self.label.setText(_translate("MainWindow", "Login"))
        self.lblusername.setPlaceholderText(_translate("MainWindow", "Username:"))
        self.lblpassword.setPlaceholderText(_translate("MainWindow", "Password:"))
        self.btnlogin.setText(_translate("MainWindow", "Login"))
        self.label_4.setText(_translate("MainWindow", "Forgot your Password ?"))
        self.btnforgopass.setText(_translate("MainWindow", "Click Here"))
        self.lbl_forgo_username.setPlaceholderText(_translate("MainWindow", "Username:"))
        self.label_5.setText(_translate("MainWindow", "Enter your username"))
        self.btnnext.setText(_translate("MainWindow", "Next"))
        self.lblfcode.setPlaceholderText(_translate("MainWindow", "Code:"))
        self.label_8.setText(_translate("MainWindow", "Enter the code"))
        self.btncheck_2.setText(_translate("MainWindow", "Check"))
        self.lblnewpass.setPlaceholderText(_translate("MainWindow", "New Pasword:"))
        self.lblnewpassre.setPlaceholderText(_translate("MainWindow", "Repeat Pasword:"))
        self.btnsub.setText(_translate("MainWindow", "SubMit"))
        self.label_6.setText(_translate("MainWindow", "Reset Password"))
        self.lbluser.setPlaceholderText(_translate("MainWindow", "Username:"))
        self.lblpass.setPlaceholderText(_translate("MainWindow", "Password:"))
        self.btnsignup.setText(_translate("MainWindow", "Signup"))
        self.label_3.setText(_translate("MainWindow", "Sign up"))
        self.lblemail.setPlaceholderText(_translate("MainWindow", "Email:"))
        self.lblrepeatpass.setPlaceholderText(_translate("MainWindow", "Repeat Pasword:"))


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     MainWindow = QtWidgets.QMainWindow()
#     ui = Ui_MainWindow()
#     ui.setupUi(MainWindow)
#     MainWindow.show()
#     sys.exit(app.exec_())
